pipeline {
    agent {
        docker {
            image 'eclipse-temurin:21'
        }
    }

    stages {
        stage('Compile') {
            steps {
                dir('hello-jenkins') {
                    sh 'javac HelloWorld.java'
                }
            }
        }

        stage('Run') {
            steps {
                dir('hello-jenkins') {
                    sh 'java HelloWorld'
                }
            }
        }
    }
}
