pipeline {
    agent any

    stages {

        stage('Checkout') {
            steps {
                checkout scm
            }
        }

        stage('Build Docker Image') {
            steps {
                dir('hello-jenkins') {
                    sh 'docker build -t hello-java:${BUILD_NUMBER} .'
                }
            }
        }

        stage('Run Container') {
            steps {
                sh 'docker run --rm hello-java:${BUILD_NUMBER}'
            }
        }

        stage('Cleanup') {
            steps {
                sh 'docker rmi hello-java:${BUILD_NUMBER}'
            }
        }
    }
}
